version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      python-prod:
        patterns:
          - "*"
        exclude-patterns:
          - "*pytest*"
          - "*flake8*"
          - "*black*"
          - "*mypy*"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 5
