codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

  ignore:
    - "tests/*"
    - "integration_test/*"
    - "setup.py"
    - "docs/*"
    - "*/__init__.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
