# Maintainer: Aydin Abdi<
# Homepage:
# License: MIT
# Summary: A package/library for linting test schema.
# Doc URL: https://readthedocs.org/projects/ats-linter/

package:
  name: ats-linter
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

source:
  git_url: https://github.com/aydabd/ats-linter.git
  git_rev: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - ats-linter = ats_linter.cli:run

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - ats_linter

about:
  home: https://github.com/aydabd/ats-linter.git
  license: MIT
  summary: A package/library for linting test schema.
  dev_url: https://github.com/aydabd/ats-linter
  doc_url: https://readthedocs.org/projects/ats-linter/

extra:
  recipe-maintainer:
    - Aydin Abdi<ayd.abd@gmail.com>
