{% set name = "ats-linter" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set url = "https://github.com/aydabd/ats-linter.git" %}
{% set license = "MIT" %}
{% set author = "aydin.a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ url }}
  git_rev: {{ version }}

build:
  number: 0
  noarch: python
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - ats-linter = ats_linter.cli:run

requirements:
  host:
    - pip
    - python >=3.11
  run:
    - python >=3.11

test:
  imports:
    - ats_linter

about:
  home: {{ url }}
  license: {{ license }}
  license_file: LICENSE.txt
  summary: A package/library for linting test schema.
  dev_url: https://github.com/aydabd/ats-linter
  doc_url: https://ats-linter.readthedocs.io/en/latest/

extra:
  recipe-maintainer:
    - {{ author }}
