name: CI/CD Test & Build

on:
  push:
    # Avoid using all the resources/limits available by checking only
    # relevant branches and tags. Other branches can be checked via PRs.
    branches: [main]
    tags: ['v[0-9]*', '[0-9]+.[0-9]+*']  # Match tags that resemble a version
  pull_request:  # Run in every PR
  workflow_dispatch:  # Allow manually triggering the workflow
  schedule:
    # Run roughly every 15 days at 00:00 UTC
    # (useful to check if updates on dependencies break the package)
    - cron: '0 0 1,16 * *'

permissions:
  contents: read

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Lints and test document on linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        tox-envs: [docs, doctests, linkcheck, lint]
    defaults:
      run:
        shell: bash -el {0}
    env:
      PIP_DEFAULT_TIMEOUT: 300
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: {fetch-depth: 0}  # deep clone for setuptools-scm
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Run tox env ${{ matrix.tox-envs }}
      run: |
        pip install --timeout=300 tox
        tox -e ${{ matrix.tox-envs }}

  test:
    name: Unit tests on linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12, 3.13]
    defaults:
      run:
        shell: bash -el {0}
    env:
      PIP_DEFAULT_TIMEOUT: 300
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: {fetch-depth: 0}  # deep clone for setuptools-scm

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests ${{ matrix.python-version }}
        run: |
          pip install --timeout=300 tox
          tox

  integration-test:
    name: Integration test (Docker)
    needs: [prepare, test]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build integration test image
        run: docker build --no-cache -f integration_test/Dockerfile -t ats-linter-integration .
      - name: Run CLI integration test
        run: |
          docker run --rm -v "$(pwd)/integration_test/test_repo:/test_repo" ats-linter-integration
      - name: Run pre-commit integration test
        run: |
          docker run --rm -v "$(pwd)/integration_test/test_repo:/test_repo" ats-linter-integration test-precommit
        # Both tests will exit nonzero if the linter fails, causing the job to fail

  build:
    needs: [prepare, test, integration-test]
    name: Build on linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox-envs: [build]
    defaults:
      run:
        shell: bash -el {0}
    env:
      PIP_DEFAULT_TIMEOUT: 300
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: {fetch-depth: 0}  # deep clone for setuptools-scm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build package
        run: |
          pip install --timeout=300 tox
          tox -e build

      - name: Upload distribution files
        uses: actions/upload-artifact@v4
        with:
          name: python-distribution-files
          path: dist/

  publish:
    needs: build
    name: Publish on PyPI
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: {fetch-depth: 0}  # deep clone for setuptools-scm
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Retrieve pre-built distribution files
        uses: actions/download-artifact@v4
        with: {name: python-distribution-files, path: dist/}
      - name: Publish Package
        env:
          # TODO: Set your PYPI_TOKEN as a secret using GitHub UI
          # - https://pypi.org/help/#apitoken
          # - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          TWINE_REPOSITORY: pypi
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install --timeout=300 tox
          tox -e publish
  deploy:
    needs: publish
    name: Deploy to Anaconda
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: {fetch-depth: 0}  # deep clone for setuptools-scm
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          auto-update-conda: false
          auto-activate-base: true
          python-version: 3.13
      - name: Deploy Package To conda-forge
        run: |
          conda install conda-build conda-verify
          conda build conda-recipe
